name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y cppcheck clang-tidy python3-pip libc6-dbg cmake libgtest-dev build-essential
          sudo apt install -y libboost-all-dev lcov
      - name: Build
        working-directory: ./hw04
        run: mkdir build && cd build && cmake .. && cmake --build .
#      - name: Lint with clang-tidy
#        working-directory: ./hw04
#        run: clang-tidy main.cpp utils/main.cpp utils/is_optimistic_from_stdin.cpp utils/is_optimistic.cpp tests/test_is_optimistic.cpp is_optimistic_synchronized/is_optimistic_synchronized.hpp is_optimistic_parallelized/is_optimistic_parallelized.hpp -extra-arg=-std=c++17
      - name: Run tests
        working-directory: ./hw04/build
        run: |
          ./tests/test_dialog_optimism_checkers
          lcov --capture -d . -o coverage.info
          lcov --remove coverage.info '/usr/*' -o coverage.info
          lcov --remove coverage.info '*/hw04/tests/*' -o coverage.info
          lcov --list coverage.info
      - name: Create test coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./hw04/build/coverage.info
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true