name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: apt install -y lcov
      - name: Build
        working-directory: ./hw02
        run: mkdir build && cd build && cmake .. && cmake --build .
      - name: Lint with clang-tidy
        working-directory: ./hw02
        run: clang-tidy include/matrix_calc.cpp -extra-arg=-std=c++17
      - name: Run tests
        working-directory: ./hw02/build
        run: |
          ./tests/test_matrix_calc
          lcov --capture -d . -o coverage.info
          lcov --remove coverage.info '/usr/*' -o coverage.info
          lcov --remove coverage.info '*/hw02/tests/*' -o coverage.info
          lcov --list coverage.info
      - name: Create test coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./hw02/build/coverage.info
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
