name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters_valgrind_cmake_gtest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update &&
          apt-get install -y lcov genhtml
      - name: Build
        working-directory: ./hw02
        run: mkdir build && cd build && cmake .. && cmake --build .
      - name: Lint with clang-tidy
        working-directory: ./hw02
        run: clang-tidy include/matrix_calc.cpp -extra-arg=-std=c++17
      - name: Run tests
        working-directory: ./hw02/build
        run: ./tests/test_matrix_calc && lcov -t "tests/tests_fib" -o coverage.info -c -d tests/ && genhtml -o report coverage.info && mv report ../tests/reports
